webtalk_init -webtalk_dir E:/III Cuatrimestre 2022/FPGA/Tareas/Proyecto/proyectoFPGA_Daniela_Rodrigo_Keylor/proyectoFPGA_Daniela_Rodrigo_Keylor.sim/sim_1/behav/xsim/xsim.dir/ContadorAnillo4bits_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Nov 23 12:40:59 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "dd63b318-8947-40de-a4dd-05df5dce6186" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "aad4ac979ced4eadacf607b1c75a5913" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "53" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4310M CPU @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2694 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.08_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6308_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4205642649 -regid "" -xml E:/III Cuatrimestre 2022/FPGA/Tareas/Proyecto/proyectoFPGA_Daniela_Rodrigo_Keylor/proyectoFPGA_Daniela_Rodrigo_Keylor.sim/sim_1/behav/xsim/xsim.dir/ContadorAnillo4bits_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/III Cuatrimestre 2022/FPGA/Tareas/Proyecto/proyectoFPGA_Daniela_Rodrigo_Keylor/proyectoFPGA_Daniela_Rodrigo_Keylor.sim/sim_1/behav/xsim/xsim.dir/ContadorAnillo4bits_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/III Cuatrimestre 2022/FPGA/Tareas/Proyecto/proyectoFPGA_Daniela_Rodrigo_Keylor/proyectoFPGA_Daniela_Rodrigo_Keylor.sim/sim_1/behav/xsim/xsim.dir/ContadorAnillo4bits_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
